completed module_6
vladSHOKO/homework pull request #1
Opened 2023-06-05 11:34 UTC by vladSHOKO

2023-06-05 18:46 UTC, Lehersun requested changes

2023-06-05 18:46 UTC, Lehersun commented on module_6/library.php
> +</html>
observe the code style please

2023-06-05 18:46 UTC, Lehersun commented on module_6/library.php
> +<p>Книга <b><?=$library['books'][3]['title']?></b>, ее написал <?=$library['authors']['martin_fauler@example.com']['name']?> <?=$library['authors']['martin_fauler@example.com']['birthYear']?> (<a hre
If you are repeating code, something has written wrong. Always think about it. Here you should use one of commands for crawling an array like 'for', 'foreach' or 'while'

2023-06-08 15:06 UTC, vladSHOKO commented on module_6/library.php
> +<p>Книга <b><?=$library['books'][3]['title']?></b>, ее написал <?=$library['authors']['martin_fauler@example.com']['name']?> <?=$library['authors']['martin_fauler@example.com']['birthYear']?> (<a hre
I know, but how can i use cycles in HTML code?

2023-06-09 08:44 UTC, Lehersun commented on module_6/library.php
> +<p>Книга <b><?=$library['books'][3]['title']?></b>, ее написал <?=$library['authors']['martin_fauler@example.com']['name']?> <?=$library['authors']['martin_fauler@example.com']['birthYear']?> (<a hre
```
<?php $elements = ['element 1', 'element 2', 'element 3']; ?>

<html>
    <body>
    <?php
    foreach ($elements as $element) { ?>
        <p> This is my element <?php echo $element ?> </p>
    <?php } ?>
    </body>
</html>

```

2023-06-17 08:50 UTC, closed without merging