Complete module_12
vladSHOKO/homework pull request #13
Opened 2023-08-07 11:07 UTC by vladSHOKO

@Lehersun
Module_12 completed

2023-11-04 14:23 UTC, Lehersun requested changes

2023-11-04 14:23 UTC, Lehersun commented on module_12/array_sort.php
> +                }
Если твой код повторяется, значит ты что-то делаешь не так. Найди способ упростить. Постарайся найти разницу в операциях и вынести ее за пределы данной операции

2023-11-04 14:23 UTC, Lehersun commented on module_12/array_sort.php
> +function arraySort(array $array, $key = 'sort', $sort = SORT_ASC): array
Так как мы начали изучать функции я хочу чтобы ты типизировал все входящие параметры функций. https://www.php.net/manual/ru/language.types.declarations.php

2023-11-05 13:17 UTC, vladSHOKO commented
@Lehersun task is ready to check!

2023-11-05 16:17 UTC, Lehersun commented on module_12/array_sort.php
> +                }
Perfect!

2023-11-05 16:17 UTC, merged