Try to complete module_13
vladSHOKO/homework pull request #14
Opened 2023-08-09 14:00 UTC by vladSHOKO

@Lehersun sorry, i dont understand. How can i use link correctly?
In file 'about' module_13/route/about.php

2023-11-04 14:24 UTC, Lehersun commented
Давай оставим до тех пор пока 11 не будет готов

2023-11-11 11:18 UTC, vladSHOKO commented
@Lehersun task is ready to check!

2023-11-11 17:51 UTC, Lehersun requested changes

2023-11-11 17:51 UTC, Lehersun commented on module_13/index.php
> +<?php
Index.php станет более понятным если не разбивать теги на разные файлы. В конце файла ты закрываешь тег `<html>` но при этом открываешь его в файле `header.php`. Гораздо читабельнее будет расположить здесь 
```
<html>
<head>....</head>
`include header.php`
`include body function`
`include footer.php`
</html>
```

2023-11-11 17:51 UTC, Lehersun commented on module_13/include/error_message.php
> +if (!empty($_POST)) {
`$_POST` может содержать что угодно. Думаю здесь ты хочешь проверять есть ли логин в массиве `$_POST`

2023-11-11 17:51 UTC, Lehersun commented on module_13/index.php
> +            var_dump($_SERVER['PHP_SELF']); ?>
Debug код удаляй перед отправкой мердж реквеста

2023-11-11 17:51 UTC, Lehersun commented on module_13/index.php
> +
Весь этот файл скорее всего часть header

2023-11-11 17:51 UTC, Lehersun commented on module_13/main_menu.php
> +        'path' => '/route/about.php',
`path` должен выглядеть как `/route/` или `/` для главной

2023-11-11 17:51 UTC, Lehersun commented on module_13/route/about.php
> +include "./templates/header.php";
header и footer везде одинаковые и должны быть подключены только в файле index.php

2023-11-11 17:51 UTC, Lehersun commented on module_13/route/catalog.php
> +</html>
Твой код повторяется на каждой странице. Значит ты что-то делаешь не так

2023-11-11 17:51 UTC, Lehersun commented on module_13/src/core.php
> +
Файл `core` должен содержать логику а не подключение файлов

2023-11-26 09:53 UTC, vladSHOKO commented
@Lehersun task is ready! I added the cutString function, but discovered that it does not work correctly with Cyrillic, so I tweaked it a little

2023-11-27 02:25 UTC, Lehersun commented on module_13/route/about.php
> +include "./templates/header.php";
Ты все еще подключаешь header во всех файлах содержащих body

2023-11-27 02:28 UTC, Lehersun commented on module_13/src/core.php
> +
Ты все еще подключаешь main_menu в core. Core должен содержать только функции, а main_menu должен подключаться в index.php так как это глобальная информация о menu

2023-11-27 03:01 UTC, Lehersun commented on module_13/route/contacts.php
> +pageTitle($menu); ?>
Эта часть кода может остаться в index.php чтобы избежать повторений

2023-11-27 06:26 UTC, vladSHOKO commented
@Lehersun errors corrected.

2023-11-27 17:34 UTC, vladSHOKO commented
@Lehersun task is ready to check

2023-12-01 08:15 UTC, Lehersun approved these changes

2023-12-01 08:15 UTC, Lehersun commented
@vladSHOKO, отличная работа!

2023-12-01 08:15 UTC, merged