Module 14
vladSHOKO/homework pull request #15
Opened 2023-12-03 07:27 UTC by vladSHOKO

@Lehersun Task is ready to check

2023-12-07 13:11 UTC, vladSHOKO commented
@Lehersun task is ready to check

2023-12-10 12:44 UTC, Lehersun requested changes

2023-12-10 12:44 UTC, Lehersun commented on module_14/src/core.php
> +                    unlink($_SERVER['DOCUMENT_ROOT'] . '/upload/' . $file);
Тебе нужно выполнять эти функции только если есть определенный ключ в массиве $_POST а не выполнять все время и проверять на наличие ключа внутри функции

2023-12-10 12:44 UTC, Lehersun commented on module_14/src/core.php
> +    checkType($images, $parameters);
foreach  лучше сделать на данном этапе, для того чтобы перебрать массив 1 раз а не два

2023-12-11 13:26 UTC, vladSHOKO commented
@Lehersun task is ready to check

2023-12-23 09:22 UTC, merged