Module 6
vladSHOKO/homework pull request #4
Opened 2023-06-17 09:45 UTC by vladSHOKO

Rewritten code with cicle 'foreach'

2023-06-17 09:46 UTC, vladSHOKO commented
@Lehersun module_6 ready to check

2023-06-17 12:14 UTC, Lehersun requested changes

2023-06-17 12:14 UTC, Lehersun commented on module_6/library.php
> +}
check code style here. `else` should be on the same line with `}`
like `} else {`

2023-06-19 13:25 UTC, vladSHOKO reviewed
Code style remade with help of hotkeys CTRL+ALT+L

2023-06-19 13:25 UTC, vladSHOKO commented
@Lehersun

2023-06-19 20:08 UTC, Lehersun commented
@vladSHOKO, I don't know what's really going wrong, but I still see coded style problems. Let's make it together tommorow

2023-06-20 19:24 UTC, vladSHOKO commented
@Lehersun task ready to check

2023-06-20 19:28 UTC, Lehersun commented
Well done

2023-06-20 19:28 UTC, merged