completed module_7
vladSHOKO/homework pull request #5
Opened 2023-06-17 10:21 UTC by vladSHOKO

@Lehersun module 7 ready to check

2023-06-17 12:41 UTC, Lehersun requested changes

2023-06-17 12:41 UTC, Lehersun commented on module_7/index.php
> +<?
it will not work without key word `php` it should looks like <?php

2023-06-17 12:41 UTC, Lehersun commented on module_7/templates/task_3_card.php
> +
All works fine, but page contains php warnings when trying to convert array to string. You can avoid those warnings with `error_reporting(16);
` command placed before this code

2023-06-19 13:41 UTC, vladSHOKO reviewed
@Lehersun corrected task ready to check. Was remade codestyle and corrected erros in convertation array to string

2023-06-21 06:41 UTC, vladSHOKO reviewed
@Lehersun code style remade

2023-06-21 17:45 UTC, merged